name: redis_dart
version: 0.1.0+3
description: A simple, minimalist and easy to use Redis client for Dart.
homepage: https://github.com/gabrielpacheco23/redis_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
