name: redis_client
version: 0.1.0
description: A simple and minimalist Redis client for Dart.
author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/gabrielpacheco23/redis_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
